name: lint & typescript check

on: push

defaults:
  run:
    working-directory: ./template

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn
      - run: mv _eslintrc.js .eslintrc.js && mv _prettierrc.js .prettierrc.js
      - name: Lint code
        run: yarn lint
